stages:
  - deploy

variables:
  S3_BUCKET_NAME: "s3-ktg-codedeploy-simple-webservice-834922934330-ap-east-1-an"
  AWS_REGION: "ap-east-1"
  CODEDEPLOY_NAME: "codedeploy-ktg-simple-webservice"
  CODEDEPLOY_GROUP: "codedeploy-group-ktg-simple-webservice"

deploy:
  stage: deploy
  before_script:
    - apt-get update -y
    - apt-get install -y zip unzip curl
    - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    - unzip awscliv2.zip
    - ./aws/install
  script:
    - /usr/local/bin/aws --version
    
    # 1. 윈도우 PC에서 발급받은 MFA 임시 자격 증명을 가상 환경에 환경 변수로 주입합니다.
    - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    - export AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN
    - export AWS_DEFAULT_REGION=$AWS_REGION

    # 2. 배포 대상 파일들(src, appspec.yml, scripts)만 골라서 압축합니다.
    - zip -r ./$CI_COMMIT_SHA.zip src/ appspec.yml scripts/
    
    # 3. S3 업로드 및 CodeDeploy 배포 실행
    - /usr/local/bin/aws s3 cp ./$CI_COMMIT_SHA.zip s3://$S3_BUCKET_NAME/$CI_COMMIT_SHA.zip
    - /usr/local/bin/aws deploy create-deployment --application-name $CODEDEPLOY_NAME --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name $CODEDEPLOY_GROUP --s3-location bucket=$S3_BUCKET_NAME,key=$CI_COMMIT_SHA.zip,bundleType=zip
